// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjc38dYacb2955ib1PFgJAuctO62r5rkQ',
    appId: '1:175018446443:web:b93cd1c11613497a212b2e',
    messagingSenderId: '175018446443',
    projectId: 'expensetracker-cbeb2',
    authDomain: 'expensetracker-cbeb2.firebaseapp.com',
    storageBucket: 'expensetracker-cbeb2.firebasestorage.app',
    measurementId: 'G-2XJ8SCHS6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByrHvHJ1WWZTtV45Gnu6txVemyfw67kwA',
    appId: '1:175018446443:android:a9b9e7f6d3b5ac25212b2e',
    messagingSenderId: '175018446443',
    projectId: 'expensetracker-cbeb2',
    storageBucket: 'expensetracker-cbeb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLVA6as6yFSsaESegQkf-TW5Om5_wJ1o',
    appId: '1:175018446443:ios:3fd5887459ae5736212b2e',
    messagingSenderId: '175018446443',
    projectId: 'expensetracker-cbeb2',
    storageBucket: 'expensetracker-cbeb2.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaLVA6as6yFSsaESegQkf-TW5Om5_wJ1o',
    appId: '1:175018446443:ios:3fd5887459ae5736212b2e',
    messagingSenderId: '175018446443',
    projectId: 'expensetracker-cbeb2',
    storageBucket: 'expensetracker-cbeb2.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjc38dYacb2955ib1PFgJAuctO62r5rkQ',
    appId: '1:175018446443:web:bb7b13794f7703cd212b2e',
    messagingSenderId: '175018446443',
    projectId: 'expensetracker-cbeb2',
    authDomain: 'expensetracker-cbeb2.firebaseapp.com',
    storageBucket: 'expensetracker-cbeb2.firebasestorage.app',
    measurementId: 'G-MG11BZHF2T',
  );
}
